// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVKityfkkNlisa0O3TerMs6lYw6MIB7HA',
    appId: '1:115094206839:web:afd7c9c226ea0555ec0972',
    messagingSenderId: '115094206839',
    projectId: 'fir-danki-7f8b5',
    authDomain: 'fir-danki-7f8b5.firebaseapp.com',
    storageBucket: 'fir-danki-7f8b5.appspot.com',
    measurementId: 'G-QTREYWXDSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFebB0lyfgwAK0fXgUNiulZqpwbiCNZ_0',
    appId: '1:115094206839:android:2583da8d6d34dc6dec0972',
    messagingSenderId: '115094206839',
    projectId: 'fir-danki-7f8b5',
    storageBucket: 'fir-danki-7f8b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmt6XaIeVUg0THxol4-c4xspswob1iNFU',
    appId: '1:115094206839:ios:5db7508e11ed42faec0972',
    messagingSenderId: '115094206839',
    projectId: 'fir-danki-7f8b5',
    storageBucket: 'fir-danki-7f8b5.appspot.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmt6XaIeVUg0THxol4-c4xspswob1iNFU',
    appId: '1:115094206839:ios:5db7508e11ed42faec0972',
    messagingSenderId: '115094206839',
    projectId: 'fir-danki-7f8b5',
    storageBucket: 'fir-danki-7f8b5.appspot.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVKityfkkNlisa0O3TerMs6lYw6MIB7HA',
    appId: '1:115094206839:web:c639205b3310d970ec0972',
    messagingSenderId: '115094206839',
    projectId: 'fir-danki-7f8b5',
    authDomain: 'fir-danki-7f8b5.firebaseapp.com',
    storageBucket: 'fir-danki-7f8b5.appspot.com',
    measurementId: 'G-XCNS7HV1YF',
  );
}
